name: Build and deploy Node.js app to Azure Web App - sachApiFeTest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Cache submodules
        uses: actions/cache@v4
        with:
          path: .git/modules
          key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-submodules-

      - name: Update submodules
        run: git submodule update --init --depth 1

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build artifact
        run: |
          npm install # Ensure all dependencies are installed
          mkdir -p dist
          cp -r src package.json package-lock.json dist/
          cd dist
          npm install --production # Install only production dependencies
          zip -r ../node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip node-app.zip -d .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_067463A9BE5A43E9B26FFF5D6FEFD6C7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C75FF53157154651AC8AB3A31806A50F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_604AE3CF73FE4696B251DCAC21DCA529 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sachApiFeTest'
          slot-name: 'Production'
          package: .